<?php
/**
 * @file
 * content_bean_footer.bean.inc
 */

/**
 * Implements hook_bean_admin_ui_types().
 */
function content_bean_footer_bean_admin_ui_types() {
  $export = array();

  $bean_type = new stdClass();
  $bean_type->disabled = FALSE; /* Edit this to true to make a default bean_type disabled initially */
  $bean_type->api_version = 5;
  $bean_type->name = 'extern';
  $bean_type->label = 'extern';
  $bean_type->options = '';
  $bean_type->description = '';
  $export['extern'] = $bean_type;

  return $export;
}
