<?php
/**
 * @file
 * content_bean.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function content_bean_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'bean-banner-field_inhoud'
  $field_instances['bean-banner-field_inhoud'] = array(
    'bundle' => 'banner',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'bean',
    'field_name' => 'field_inhoud',
    'label' => 'Inhoud',
    'required' => 0,
    'settings' => array(
      'display_summary' => 0,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 31,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Inhoud');

  return $field_instances;
}
